routes/admin.php
<?php


/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register Admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "admin" middleware group. Enjoy building your Admin!
|
*/
//Route::view('/', 'Admin.index');
//
//Auth::routes();
//
//Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm');
//Route::get('/register/admin', 'Auth\RegisterController@showAdminRegisterForm');
//
//Route::post('/login/admin', 'Auth\LoginController@adminLogin');
//Route::post('/register/admin', 'Auth\RegisterController@createAdmin');
//
//Route::view('/admin', 'admin');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models;
use Carbon\Carbon;

URL::forceScheme('https');

//route for aoutologin link
Route::get('/autologin/{model}', function (Models $model) {
    Auth::guard('model')->login($model);
    $model->email_verified_at = Carbon::now();
    $model->save();
    return redirect()->route('models.approval');
})->name('autologin');

//route for phoneaoutologin link
Route::get('/autologinphone/{model}', function (Models $model) {
    Auth::guard('model')->login($model);

    $model->phone_verified_at = Carbon::now();
    $model->save();

    return redirect()->route('models.approval');
})->name('autologinphone');

    Route::view('/', 'Models.index');

// Authentication Routes...
//models
    Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\LoginController@login');
    Route::any('/logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
    Route::get('/register', 'Auth\ModelRegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'Auth\ModelRegisterController@create')->name('register_post');

// Password Reset Routes...
    Route::post('/password/email','Auth\ModelForgotPasswordController@sendResetLinkEmail')->name('model.password.email');
    Route::post('/password/reset', 'Auth\ModelResetPasswordController@reset');
    Route::get('/password/reset', 'Auth\ModelForgotPasswordController@showLinkRequestForm')->name('model.password.request');
    Route::get('/password/reset/{token}', 'Auth\ModelResetPasswordController@showResetForm')->name('model.password.reset');


    Route::any('/ajaxData', 'AjaxController@locationSelect');
    Route::any('/resendphonelink', 'AjaxController@resendPhoneLink');
    Route::any('/resendemaillink', 'AjaxController@resendEmailLink');
    Route::any('/changePhone', 'AjaxController@changePhone');
    Route::any('/changeEmail', 'AjaxController@changeEmail');

    Route::prefix('admin')->group(function () {

        //admin login
        Route::get('/login', 'Auth\AdminLoginController@showAdminLoginForm')->name('admin.login');
        Route::post('/login', 'Auth\AdminLoginController@adminLogin');

        //admin register
        Route::get('/register', 'Auth\RegisterController@showAdminRegisterForm');
        Route::post('/register', 'Auth\RegisterController@createAdmin');

        //admin password reset routes
        Route::post('/password/email','Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::post('/password/reset','Auth\AdminResetPasswordController@reset');
        Route::get('/password/reset','Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::get('/password/{token}','Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');


        Route::group(['middleware' => ['admin']], function() {

            //admin home page
            Route::any('/', 'Admin\HomeController@index')->name('admin.home');
            Route::post('/stats', 'Admin\HomeController@stats');
            Route::any('/updatestudio', 'Admin\HomeController@updatestudio')->name('admin.updatestudio');

            //models page
            Route::resource('/models','ModelsController');

            Route::any('/allmodels','ModelsController@all_models');
            Route::any('/approvedmodels','ModelsController@approved_models');
            Route::any('/pendingmodels','ModelsController@pending_models');
            Route::any('/suspendedmodels','ModelsController@suspended_models');
            Route::any('/rejectedmodels','ModelsController@rejected_models');
            Route::any('/inactivemodels','ModelsController@inactive_models');

            //model profile -> TO DO should check if user has access to model
            Route::get('/model/{id}','ModelsController@profile');
            Route::post('/model/{id}','ModelsController@edit_profile');
            Route::post('/modelnickname','ModelsController@set_nickname');
            Route::post('/ignoreres','ModelsController@ignore_reservations');

            //Payments
            Route::get('/insertsales', 'Admin\PaymentsController@index')->name('admin.insertsales');
            Route::post('/addsales', 'Admin\SalesController@addsales')->name('admin.addsales');
            Route::any('/makepayment', 'Admin\PaymentsController@makepayment')->name('admin.makepayment');
            Route::any('/paymenthistory', 'Admin\PaymentsController@paymenthistory')->name('admin.paymenthistory');
            Route::any('/makepaymentid', 'Admin\PaymentsController@makepaymentid')->name('admin.makepaymentid');
            Route::get('/viewsales/{modelid}/{year}/{period}', 'Admin\SalesController@viewsales')->name('admin.viewsales');
            Route::get('/viewsale/{id}', 'Admin\SalesController@viewsale');
            Route::post('/viewsale/update', 'Admin\SalesController@updatesale');
            Route::delete('/viewsale/{id}', 'Admin\SalesController@deletesale');

            Route::any('/closeperiod', 'Admin\PaymentsController@closeperiods')->name('admin.closeperiods');
            Route::get('/closeperiodid/{periodid}', 'Admin\SalesController@closeperiod');
            Route::get('/closeperiods/{periodid}', 'Admin\PaymentsController@closeperiod');
            Route::post('/closeperiodid/{periodid}', 'Admin\PaymentsController@closeperiodid');
            Route::post('/openperiod', 'Admin\PaymentsController@openperiod');
            Route::post('/checkSales', 'Admin\PaymentsController@checkPeriodSales');
            Route::post('/updateSalesPeriod', 'Admin\PaymentsController@updateSalesPeriod');

            //Sales from Api
            Route::post('/getsalesmodel', 'JasminApiController@getSalesDay');
            Route::get('/getsalesperiod/{modelname}/{year}/{period}', 'JasminApiController@getSalesPeriod');

            //Messages
            Route::get('/inbox', 'Admin\MessageController@index')->name('admin.inbox');
            Route::get('/message/{id}', 'Admin\MessageController@show');
            Route::post('/message/{id}', 'Admin\MessageController@insert');
            Route::any('/composemessage', 'Admin\MessageController@composemessage')->name('admin.composemessage');
            Route::post('/onebyone', 'Admin\MessageController@onebyone')->name('admin.onebyone');
            Route::post('/sendtoone', 'Admin\MessageController@sendtoone')->name('admin.sendtoone');
            Route::get('/messagessent', 'Admin\MessageController@messagessent')->name('admin.messagessent');
            Route::get('/solved', 'Admin\MessageController@solved')->name('admin.solved');
            Route::post('/autotype', 'Admin\MessageController@autotype');

            //Reservations
            Route::any('/reservations', 'Admin\ReservationsController@index')->name('admin.reservations');
            Route::any('/reservations/{id}', 'Admin\ReservationsController@show');

            //studio edit page (admins only, etc)
            Route::resource('/studios','Admin\StudioController');

            //roles page
            //Route::resource('/roles','Admin\RolesController');

            //twitter page
            Route::get('/twitter', 'Admin\TwitterController@index')->name('admin.twitter');

            //users
            Route::any('/users', 'Admin\EditAdminsController@index')->name('admin.users');
            Route::get('/users/roles', 'Admin\EditAdminsController@roles');
            Route::get('/users/studios', 'Admin\EditAdminsController@studios');

            Route::get('/users/{id}', 'Admin\EditAdminsController@viewUser');
            Route::post('/usersid', 'Admin\EditAdminsController@editUser');
            Route::delete('/users/{id}', 'Admin\EditAdminsController@deleteUser');

            //notifications
            Route::post('/notifications', 'Admin\NotificationController@index')->name('admin.notifications');
            Route::post('/notificationsreadtime', 'Admin\NotificationController@addReadTime');

            //log
            Route::get('/log', 'Admin\LogController@index')->name('admin.log');

            //news
            Route::get('/news', 'Admin\NewsController@index')->name('admin.news');

            //background jobs
            Route::get('/backgroundservice', 'Admin\BackgroundController@index')->name('admin.backgroundservice');
            Route::get('/getsales', 'Admin\BackgroundController@getsales')->name('admin.getsales');
            Route::get('/getsalesallmodels', 'Admin\BackgroundController@getsalesallmodels')->name('admin.getsalesallmodels');
            Route::post('/getsalesallperiod', 'Admin\BackgroundController@getsalesallperiod')->name('admin.getsalesallperiod');

            //Generate Contract
            Route::post('/generate_contract', 'Admin\GenerateContractController@store')->name('admin.generate_contract');
            Route::get('/contracts/contract_{slug}.pdf', [
                'as' => 'contracts.show',
                'uses' => 'Admin\GenerateContractController@showContract',
            ]);


            //settings
            Route::get('/settings', 'Admin\SettingsController@index')->name('admin.settings');

            //notifications
            Route::post('/testnotification', 'NotificationsController@test')->name('admin.notifications');

            //admin logout
            Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');

            Route::resource('user', 'UserController', ['except' => ['show']]);

app/Models.php
<?php

namespace App;

use App\Notifications\ModelResetPasswordNotification;
use Illuminate\Database\Eloquent\Model;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Models extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    protected $table = 'models';

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ModelResetPasswordNotification($token));
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function profile(){
        return $this->hasOne('App\ModelProfile', 'model_id');
    }

    public function studios(){
        return $this->hasOne('App\Studio', 'id', 'studio');
    }

    public function statusName(){
        return $this->hasOne('App\ModelStatus', 'id', 'status');
    }

    public function address(){
        return $this->hasOne('App\ModelAddress', 'model_id');
    }

    public function paymentDetails(){
        return $this->hasOne('App\ModelPaymentDetail', 'model_id');
    }

    public function social(){
        return $this->hasOne('App\ModelSocial', 'model_id');
    }

    public function contract(){
        return $this->hasOne('App\ModelContract', 'model_id');
    }

    public function key(){
        return $this->hasOne('App\ApiKeys', 'id', 'key_id');
    }

    public function account(){
        return $this->hasOne('App\ModelAccount', 'model_id');
    }

    public function signature(){
        return $this->hasOne('App\ModelSignature', 'model_id');
    }

    public function feedback(){
        return $this->hasMany('App\ModelFeedback', 'model_id');
    }

    public function periods(){
        return $this->hasMany('App\ModelPeriod', 'model_id')->orderBy('year','ASC')->orderBy('period','ASC');
    }

    public function paymentHistory(){
        return $this->hasMany('App\ModelPaymentHistory', 'model_id');
    }


}

resources/views/Admin/models/allmodels.blade.php
@extends('layouts.admin_app', ['activePage' => 'models', 'titlePage' => __('Models')])

@push('head')

@endpush

@section('content')

    <style>

        hr{
            background: #f44336;
        }
        th {
            font-weight: bolder!important;
        }
        .card-header{
            background: #fff!important;
        }
        .card-title{
            color: #000!important;
        }
    </style>

    <div class="content">

        <div class="container-fluid">
            <div class="row">

                <div class="card">
                    <div class="card-header card-header-success">
                        <h4 class="card-title">All Models</h4>
                        <hr>
                    </div>
                    <div class="card-body table-responsive">
                        <table id="allModels" class="table table-hover data-table table-striped table-bordered">
                            <thead>
                            <tr >
                                {{--<th>No</th>--}}
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Email</th>
                                <th>Nickname</th>
                                <th>Studio</th>
                                <th>Status</th>
                                <th>Promo</th>
                                <th>Signup</th>
                                {{--<th>First Login</th>--}}
                            </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>

            </div>

        </div>

    </div>

@endsection

@push('js')
<script>

    let table;
    let tableBody = $('tbody');
    let studio = $("#myStudio").children("option:selected").val();

    $(document).ready(function() {

        tableBody.on('click', 'tr', function () {
            let data = table.row( this ).data();
            //console.log(data);
            window.open("/admin/model/" + data.id);

        } );

    });

    $(function () {

        table = $('#allModels').DataTable({

            processing: true,
            "language": {
                processing: '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i><span class="sr-only">Loading...</span> '},
            serverSide: true,
            ajax: {
                'url':'/admin/allmodels',
                "type": "POST",
                "data": function (d) {
//                    d.period = period;
//                    d.year = year;
                    d.studio = studio;
                },
                'headers': {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
//            "dataSrc": function ( json ) {
//                console.log(json);
//                return json;
//            }
            },
            lengthMenu: [[25, 50, -1], [25, 50, "All"]],
            columns: [
//                {data: 'id', name: 'id', searchable: true, orderable: true},
                {data: 'profile.first_name', name: 'profile.first_name', searchable: true},
                {data: 'profile.last_name', name: 'profile.last_name', searchable: true},
                {data: 'email', name: 'email', searchable: true, orderable: true},
                {data: 'modelname', name: 'modelname', searchable: true, orderable: true},
                {data: 'studios.name', name: 'studios.name', searchable: false, orderable: false},
                {data: 'status_name.name', name: 'status_name.name', searchable: false, orderable: false},
                {data: 'social.brand', name: 'social.brand', searchable: false, orderable: false},
                {data: 'created_at', name: 'created_at', searchable: false, orderable: true},
//                {data: 'profile.first_login', name: 'profile.first_login', searchable: false, orderable: false},
            ],
            columnDefs: [ {
                "targets": 5,
                render: function (data, type, row, meta)
                {
                    if (type === 'display') data = '<b class="'+data.toLowerCase()+'">' + data + '</b>';

                    return data;
                }
            }]

        });

    });

</script>
@endpush

resources/views/Admin/models/approved_models.blade.php
@extends('layouts.admin_app', ['activePage' => 'approvedmodels', 'titlePage' => __('Dashboard')])

@push('head')

@endpush

@section('content')

    <style>

        hr{
            background: #f44336;
        }
        th {
            font-weight: bolder!important;
        }
        .card-header{
            background: #fff!important;
        }
        .card-title{
            color: #000!important;
        }
    </style>

    <div class="content" style="background: #fff;">

        <div class="container-fluid">
            <div class="row">

                <div class="card">
                    <div class="card-header card-header-success">
                        <h4 class="card-title">Models Approved</h4>
                        <hr>
                    </div>
                    <div class="card-body table-responsive">
                        <table id="approvedModels" class="table table-hover data-table table-striped table-bordered">
                            <thead >
                                <tr>
                                    <th>No</th>
                                    <th>First Name</th>
                                    <th>Last Name</th>
                                    <th>Email</th>
                                    <th>Nickname</th>
                                    <th>Studio</th>
                                    <th>Status</th>
                                    <th>Promo</th>
                                    <th>Signup</th>
                                    <th>First Login</th>
                                    <th>Last Login</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>

            </div>

        </div>

    </div>

@endsection

@push('js')
<script>

    let table;

    $(document).ready(function() {

        $('tbody').on('click', 'tr', function () {
            let data = table.row( this ).data();
            console.log(data);
            window.open("/admin/model/" + data.id);

        } );

    });

    $(function () {

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        table = $('#approvedModels').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ url('/admin/approvedmodels') }}",
            lengthMenu: [[25, 50, -1], [25, 50, "All"]],
            columns: [
                {data: 'id', searchable: false, orderable: false},
                {data: 'first_name', name:'profile.first_name', searchable: true, orderable: true},
                {data: 'last_name', name:'profile.last_name', searchable: true, orderable: true},
                {data: 'email', name:'email', searchable: true, orderable: true},
                {data: 'modelname', name:'modelname', searchable: true, orderable: true},
                {data: 'studios', name:'studios', searchable: true, orderable: true},
                {data: 'status', searchable: false, orderable: false},
                {data: 'promo', searchable: true, orderable: true},
                {data: 'created_at', searchable: false, orderable: false},
                {data: 'created_at', searchable: false, orderable: false},
                {data: 'created_at', searchable: false, orderable: false},

            ]
        });

    });

</script>
@endpush

resources/views/Admin/models/approved_models2.blade.php
@extends('layouts.admin_app', ['activePage' => 'approvedmodels', 'titlePage' => __('Dashboard')])

@push('head')

@endpush

@section('content')

    <style>

        hr{
            background: #f44336;
        }
        th {
            font-weight: bolder!important;
        }
        .card-header{
            background: #fff!important;
        }
        .card-title{
            color: #000!important;
        }
    </style>

    <div class="content" style="background: #fff;">

        <div class="container-fluid">
            <div class="row">

                <div class="card">
                    <div class="card-header card-header-success">
                        <h4 class="card-title">Models Approved</h4>
                        <hr>
                    </div>
                    <div class="card-body table-responsive">
                        <table id="approvedModels" class="table table-hover data-table table-striped table-bordered">
                            <thead >
                            <tr>
                                {{--<th>No</th>--}}
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Email</th>
                                <th>Nickname</th>
                                <th>Studio</th>
                                <th>Status</th>
                                <th>Promo</th>
                                <th>Signup</th>
                                {{--<th>First Login</th>--}}
                                {{--<th>Last Login</th>--}}
                            </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>

            </div>

        </div>

    </div>

@endsection

@push('js')
<script>

    let table;
    let studio = $("#myStudio").children("option:selected").val();

    $(document).ready(function() {

        $('tbody').on('click', 'tr', function () {
            let data = table.row( this ).data();
            //console.log(data);
            window.open("/admin/model/" + data.id);

        } );

    });

    $(function () {

        table = $('#approvedModels').DataTable({
            processing: true,
            "language": {
                processing: '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i><span class="sr-only">Loading...</span> '},
            serverSide: true,
            ajax: {
                'url':'/admin/approvedmodels',
                "type": "POST",
                "data": function (d) {
                    d.studio = studio;
                },
                'headers': {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
//            "dataSrc": function ( json ) {
//                console.log(json);
//                return json;
//            }
            },
            lengthMenu: [[25, 50, -1], [25, 50, "All"]],
            columns: [
//                {data: 'id',  name: 'id', searchable: true, orderable: true},
                {data: 'profile.first_name', name:'profile.first_name', searchable: true, orderable: true},
                {data: 'profile.last_name', name:'profile.last_name', searchable: true, orderable: true},
                {data: 'email', name:'email', searchable: true, orderable: true},
                {data: 'modelname', name:'modelname', searchable: true, orderable: true},
                {data: 'studios.name', name:'studios.name', searchable: true, orderable: true},
                {data: 'status_name.name', searchable: false, orderable: false},
                {data: 'social.brand', searchable: true, orderable: true},
                {data: 'created_at', searchable: false, orderable: true},

            ],
            columnDefs: [ {
                "targets": 5,
                render: function (data, type, row, meta)
                {
                    if (type === 'display') data = '<b class="'+data.toLowerCase()+'">' + data + '</b>';

                    return data;
                }
            }]
        });

    });

</script>
@endpush

resources/views/Admin/models/suspended_models.blade.php
@extends('layouts.admin_app', ['activePage' => 'suspendedmodels', 'titlePage' => __('Dashboard')])

@push('head')

@endpush

@section('content')

    <style>

        hr{
            background: #f44336;
        }
        th {
            font-weight: bolder!important;
        }
        .card-header{
            background: #fff!important;
        }
        .card-title{
            color: #000!important;
        }
    </style>

    <div class="content" >

        <div class="container-fluid">
            <div class="row">

                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title">Models Suspended</h4>
                        <hr>
                    </div>
                    <div class="card-body table-responsive">
                        <table id="suspendedModels" class="table table-hover data-table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Email</th>
                                <th>Nickname</th>
                                <th>Studio</th>
                                <th>Status</th>
                                <th>Signup</th>
                            </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>

            </div>

        </div>

    </div>

@endsection

@push('js')
<script>

    let table;
    let tableBody = $('tbody');
    let studio = $("#myStudio").children("option:selected").val();


    $(document).ready(function() {

        tableBody.on('click', 'tr', function () {
            let data = table.row( this ).data();
            //console.log(data);
            window.open("/admin/model/" + data.id);

        } );

    });
    $(function () {

        table = $('#suspendedModels').DataTable({
            processing: true,
            "language": {
                processing: '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i><span class="sr-only">Loading...</span> '},
            serverSide: true,
            ajax: {
                'url':'/admin/suspendedmodels',
                "type": "POST",
                "data": function (d) {
                    d.studio = studio;
                },
                'headers': {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
//            "dataSrc": function ( json ) {
//                console.log(json);
//                return json;
//            }
            },
            lengthMenu: [[25, 50, -1], [25, 50, "All"]],
            columns: [
//                {data: 'id',  name: 'id', searchable: true, orderable: true},
                {data: 'profile.first_name', name:'profile.first_name', searchable: true, orderable: true},
                {data: 'profile.last_name', name:'profile.last_name', searchable: true, orderable: true},
                {data: 'email', name:'email', searchable: true, orderable: true},
                {data: 'modelname', name:'modelname', searchable: true, orderable: true},
                {data: 'studios.name', name:'studios.name', searchable: true, orderable: true},
                {data: 'status_name.name', searchable: false, orderable: false},
//                {data: 'social.brand', searchable: true, orderable: true},
                {data: 'created_at', searchable: false, orderable: true},
            ],
            columnDefs: [ {
                "targets": 5,
                render: function (data, type, row, meta)
                {
                    if (type === 'display') data = '<b class="'+data.toLowerCase()+'">' + data + '</b>';

                    return data;
                }
            }]
        });

        $('#createNewProduct').click(function () {
            $('#saveBtn').val("create-product");
            $('#product_id').val('');
            $('#productForm').trigger("reset");
            $('#modelHeading').html("Create New Product");
            $('#ajaxModel').modal('show');
        });

        $('body').on('click', '.editProduct', function () {
            var product_id = $(this).data('id');
            $.get("{{ route('models.index') }}" +'/' + product_id +'/edit', function (data) {
                $('#modelHeading').html("Edit Product");
                $('#saveBtn').val("edit-user");
                $('#ajaxModel').modal('show');
                $('#product_id').val(data.id);
                $('#name').val(data.name);
            })
        });

        $('#saveBtn').click(function (e) {
            e.preventDefault();
            $(this).html('Sending..');

            $.ajax({
                data: $('#productForm').serialize(),
                url: "{{ route('models.store') }}",
                type: "POST",
                dataType: 'json',
                success: function (data) {

                    $('#productForm').trigger("reset");
                    $('#ajaxModel').modal('hide');
                    table.draw();

                },
                error: function (data) {
                    console.log('Error:', data);
                    $('#saveBtn').html('Save Changes');
                }
            });
        });

        $('body').on('click', '.deleteProduct', function () {

            var product_id = $(this).data("id");
            confirm("Are You sure want to delete !");

            $.ajax({
                type: "DELETE",
                url: "{{ route('models.store') }}"+'/'+product_id,
                success: function (data) {
                    table.draw();
                },
                error: function (data) {
                    console.log('Error:', data);
                }
            });
        });

    });

</script>
@endpush